name: GifCreator
version: '1.0.0'
main: dev.lemontree.gifcreator.GifCreator
api-version: '1.19'
commands:
  gif:
    description: Searches a GIF on GIPHY using a search term
    usage: /gif [search]
    permission: gifcreator.gif
